### ISSUE TITLE
Can't find PP value for Loved Maps

### ISSUE THREAD

**Issue by natestutte** [imacrazyguylol/pythumbnail#4]
![image](https://github.com/imacrazyguylol/pythumbnail/assets/37859882/4f3fe207-a54b-4dad-afae-aad4372250af)

Score: https://osu.ppy.sh/scores/osu/4376488361

When attempting to pass through a score of a loved map, the PP value it obtains is set as a NoneType (as loved maps do not give PP). The error pops up when trying to round this specific type for drawing.

**Comment by wfrowell** [comment]
should be resolved in latest commit
